### Setup
First, load the model.

In [1]:
from modeling_gpt2 import GPT2Model, GPT2LMHeadModel
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2", cache_dir="hf_home/")
# model = GPT2Model.from_pretrained("gpt2", cache_dir="hf_home/")  # for forward pass
model = GPT2LMHeadModel.from_pretrained("gpt2", cache_dir="hf_home/")  # for generation
model.cuda()

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

### Initial Testing for Correctness
Now, let's do forward passes on some sample inputs. Starting with the baseline.

In [3]:
inputs = tokenizer(["Today is"], return_tensors="pt").to('cuda')
model.transformer.config._attn_implementation = "sdpa"  # NOTE: This is default, but we set manually here for emphasis.
out = model.forward(inputs['input_ids'])
out.logits

tensor([[[ -36.3292,  -36.3402,  -40.4228,  ...,  -46.0234,  -44.5284,
           -37.1276],
         [-122.8355, -122.5403, -127.6362,  ..., -133.4906, -131.9769,
          -125.4615]]], device='cuda:0', grad_fn=<UnsafeViewBackward0>)

Now, using the minimal-flash-attn default attention implementation. Default is `sdpa`.

In [51]:
inputs = tokenizer(["Today is"], return_tensors="pt").to('cuda')
model.transformer.config._attn_implementation = "mha_forward"
out = model.forward(inputs['input_ids'])
out.logits

tensor([[[-60.7520, -57.8984, -62.9119,  ..., -73.0113, -72.7144, -62.5149],
         [-75.0848, -68.3251, -73.7947,  ..., -78.2720, -80.7028, -72.4456]]],
       device='cuda:0', grad_fn=<UnsafeViewBackward0>)

*Note*: These logits are different -- there's likely some problem with the gpu memory. If I run this multiple times, gpu memory goes up without getting cleaned up.

Now using our improved version.

In [102]:
inputs = tokenizer(["Today is"], return_tensors="pt").to('cuda')
model.transformer.config._attn_implementation = "improved_mha_forward"
out = model.forward(inputs['input_ids'])
out.logits

tensor([[[-109.7571, -107.5167, -112.4549,  ..., -128.1173, -126.5531,
          -112.4645],
         [-190.6232, -186.3232, -197.7389,  ..., -202.0215, -212.6783,
          -189.7682]]], device='cuda:0', grad_fn=<UnsafeViewBackward0>)

### Initial Testing for Timing
Great! We can see the shapes are the same and the output tensors are too. This means the attention implementation is correct. Now, let's see if it is faster.

In [103]:
import os
os.makedirs("traces", exist_ok=True)

In [104]:
import torch
import time
attn_implementations = ["sdpa", "mha_forward", "improved_mha_forward"]
for attn_implementation in attn_implementations:
    print(f'=== profiling `{attn_implementation}` attention === ')
    model.transformer.config._attn_implementation = attn_implementation
    with torch.autograd.profiler.profile(use_device='cuda') as prof:
        start_time = time.time()
        out = model.forward(inputs['input_ids'])
        end_time = time.time()
    prof.export_chrome_trace(f"traces/{attn_implementation}_trace.json")  # note we can inspect these with chrome://tracing/
    print(prof.key_averages().table(sort_by='cuda_time_total', row_limit=10))
    print(f"Total time taken: {end_time - start_time}\n\n")

=== profiling `sdpa` attention === 
-------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                             Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                      aten::addmm        10.08%       4.340ms        15.34%       6.607ms     137.648us       5.699ms        12.98%       7.314ms     152.375us            48  
                                 aten::layer_norm         1.11%     477.823us        14.64%       6.307ms     252.295us     648.000us         1.48%       6.513ms     260.520us            25  
   

Note we see that the default minimal flash attn implementation is faster by ~7ms! And we can see the `aten::scaled_dot_product_attention` runs for the baseline and our `minimal_attn::mha_forward kernel` replaces it, as desired. For now, it does appear to take slightly more CUDA time, which makes sense as we have to use more memory -- the original version probably has more to do on the CPU. In the future we will test how that varies with different input sizes.

| Name                                     | Self CPU %   | Self CPU    | CPU total % | CPU total   | CPU time avg | Self CUDA   | Self CUDA % | CUDA total  | CUDA time avg | # of Calls |
| :--------------------------------------- | :----------- | :---------- | :---------- | :---------- | :----------- | :---------- | :---------- | :---------- | :------------ | :--------- |
| `aten::scaled_dot_product_attention`     | 0.67%        | 213.412us   | 9.23%       | 2.931ms     | 244.211us    | 302.000us   | 1.27%       | 2.978ms     | 248.167us     | 12         |
| `minimal_attn::mha_forward`              | 1.01%        | 162.292us   | 8.00%       | 1.285ms     | 107.096us    | 2.465ms     | 14.54%      | 3.323ms     | 276.917us     | 12         |

In [ ]:
# Create a bunch of inputs with random tokens.
# Note we are not doing real words bc we are not dealing with masking right now
# and there should be no need.


### Generation
Let's try generation now before starting the benchmarking.

In [105]:
# Generate text
import torch
import time

def generate_and_decode(model, inputs):
    with torch.no_grad():
        output_ids = model.generate(
            inputs['input_ids'],
            max_new_tokens=100,
            num_return_sequences=1,
            do_sample=False
        )
        print(tokenizer.decode(output_ids[0]))

def run_with_tracing(inputs, attn_implementation):
    print(f'=== profiling `{attn_implementation}` attention === ')
    model.transformer.config._attn_implementation = attn_implementation
    with torch.autograd.profiler.profile(use_device='cuda') as prof:
        start_time = time.time()
        out = generate_and_decode(model, inputs)
        end_time = time.time()
    # prof.export_chrome_trace(f"traces/{attn_implementation}_generation_trace.json")  # note we can inspect these with chrome://tracing/
    print(prof.key_averages().table(sort_by='cuda_time_total', row_limit=10))
    print(f"Total time taken: {end_time - start_time}\n\n")

In [106]:
inputs = tokenizer(["Today is"], return_tensors="pt").to('cuda')
attn_implementations = ["sdpa", "mha_forward", "improved_mha_forward"]
for attn_implementation in attn_implementations:
    run_with_tracing(inputs, attn_implementation)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


=== profiling `sdpa` attention === 
Today is the day when we can all be proud of our country and our values.

We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all Americans. We are all


The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                            aten::addmm        10.44%     257.981ms        16.18%     400.007ms      83.335us     411.504ms        16.28%     480.761ms     100.159us          4800  
                                       aten::layer_norm         1.27%      31.409ms        14.28%     352.953ms     141.181us      45.801ms         1.81%     366.812ms     146.725us          2500  
         

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
